graph TD
   	eDeviceDiscovery -->eFoundDevice
    eFoundDevice--"Connect()"-->eConnecting
    eConnecting--"ConnectionCB()"-->eConnected
    eConnected--"StartServiceDiscovery()"-->eServiceDiscovery
    eServiceDiscovery--"ServiceCharacteristicsCB()"-->eFoundServiceCharacteristic_0x2A5B
    eServiceDiscovery--"ServiceDiscoveryCB()"-->noting
    eFoundServiceCharacteristic_0x2A5B--"ServiceDiscoveryTerminationCB()"-->eDiscoverCharacteristicDescriptors
    eDiscoverCharacteristicDescriptors--"DiscoveredDescCB()"-->eFoundCharacteristicDescriptor_0x2902
    eFoundCharacteristicDescriptor_0x2902--"DiscoveredDescTerminationCB()"-->eRequestNotify
    eRequestNotify--"RequestNotify()"-->eRunning
    eDisconnected--"Connect()"-->eConnecting
    eRunning-->eDisconnected